version: '3'
services:
    kamailio:
        container_name: kamailio
        build:
            context: .
            dockerfile: kamailio/dockerfile
        image: kamailio-vp
        ports:
            - "5061:5061"
        networks:
            call-asterisk:
                ipv4_address: 172.0.0.2

    postgres:
        container_name: postgres
        image: postgres:bullseye
        deploy:
            resources:
                limits:
                    memory: 1024M
        restart: always
        environment:
            - POSTGRES_DB=skeleton_sms
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - type: bind
              source: /home/vpl3ntz/PhpstormProjects/call-asterisk/postgres/data
              target: /var/lib/postgresql/data
        networks:
            call-asterisk:
                ipv4_address: 172.0.0.3

    redis:
        container_name: redis
        image: redis:latest
        deploy:
            resources:
                limits:
                    memory: 1024M
        volumes:
            - type: bind
              source: /home/vpl3ntz/PhpstormProjects/call-asterisk/redis/data
              target: /data
        networks:
            call-asterisk:
                ipv4_address: 172.0.0.4

#    pgadmin:
#        container_name: pgadmin
#        image: dpage/pgadmin4:latest
#        deploy:
#            resources:
#                limits:
#                    memory: 1024M
#        restart: always
#        environment:
#            - PGADMIN_DEFAULT_EMAIL=test@test.com
#            - PGADMIN_DEFAULT_USERNAME=postgres
#            - PGADMIN_DEFAULT_PASSWORD=postgres
#        ports:
#            - "80:80"
#        hostname: pgadmin
#        depends_on:
#            - postgres
#        networks:
#            call-asterisk:
#                ipv4_address: 172.0.0.5

networks:
    call-asterisk:
        driver: bridge
        ipam:
          config:
            - subnet: 172.0.0.0/16
              gateway: 172.0.0.1

