FROM debian:bullseye

RUN apt update &&\
    apt upgrade &&\
    apt install -y \
    curl \
    git \
    subversion \
    nano \
    make && \
    cd /usr/src/ &&\
    git clone https://github.com/asterisk/asterisk.git && \
    cd asterisk/ && \
    contrib/scripts/get_mp3_source.sh && \
    contrib/scripts/install_prereq install && \
    cd /tmp/ && \
    wget https://raw.githubusercontent.com/asterisk/third-party/master/pjproject/2.13.1/pjproject-2.13.1.tar.bz2 && \
    cd /usr/src/asterisk/ && \
    ./configure

ENTRYPOINT ["top", "-b"]
