FROM debian:bullseye
ENTRYPOINT ["kamailio", "-DD", "-E"]
RUN apt update -y &&\
    apt upgrade -y &&\
    apt install -y kamailio\
    sngrep \
    nano \
    rsyslog \
    kamailio-redis-modules \
    kamailio-postgres-modules \
    iputils-ping


RUN mkdir "./config_kamailio"
COPY /kamailio/kamailio.cfg ./config_kamailio
COPY /kamailio/kamctlrc ./config_kamailio

