FROM debian:bullseye
ENTRYPOINT ["top", "b"]
RUN apt update -y &&\
    apt upgrade -y &&\
    apt install -y kamailio\
    procps \
    sngrep \
    nano \
    rsyslog \
    kamailio-redis-modules \
    kamailio-postgres-modules \
    iputils-ping


RUN mkdir "./config_kamailio"
COPY /kamailio/kamailio.cfg ./config_kamailio
COPY /kamailio/kamctlrc ./config_kamailio

